name: Release Packaging

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [published]

jobs:
  package-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 需要权限来修改 Release

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Validate source directory
      run: |
        if [ ! -d "Flashback Translations" ]; then
          echo "::error::❌ 源目录 'Flashback Translations' 不存在"
          exit 1
        fi

    - name: Create ZIP package
      run: |
        cd "Flashback Translations"
        zip -r ../Flashback-Translations-NEXT.zip .
        echo "PACKAGE_PATH=$(pwd)/../Flashback-Translations-NEXT.zip" >> $GITHUB_ENV

    - name: Upload Artifact (Non-Release)
      if: github.event_name != 'release'
      uses: actions/upload-artifact@v4
      with:
        name: Flashback-Translations-NEXT
        path: ${{ env.PACKAGE_PATH }}

    - name: Upload to Release
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{ env.PACKAGE_PATH }}
        asset_name: Flashback-Translations-NEXT.zip
        asset_content_type: application/zip
